### ISSUE TITLE
Release Bacon to Maven Central 

### ISSUE THREAD

**Issue by goldmann** [project-ncl/bacon#344]
We still do not have a released version of Bacon, but we cannot work on SNAPSHOT's anymore.

**Comment by thescouser89** [comment]
Most of the PNC bits are actually not released on Central, so that's why we can't push Bacon to central yet. We do have it on staging sonatype: https://oss.sonatype.org/content/groups/staging/org/jboss/pnc/bacon/cli/2.0.0/ , but I know this won't satisfy your requirements.

We can discuss it in our meeting.

**Comment by goldmann** [comment]
@thescouser89 I was referring to this:

```
$ bacon update
Updating to latest released version...
Downloading: https://repo.maven.org/maven2/org/jboss/pnc/bacon/cli/maven-metadata.xml
Something wrong happened while downloading the link: https://repo.maven.org/maven2/org/jboss/pnc/bacon/cli/maven-metadata.xml
```

**Comment by goldmann** [comment]
```
$ bacon --version
2.0.0-SNAPSHOT (c01951d)
```

**Comment by jbartece** [comment]
It will be released tomorrow. Closing this issue as I'm about to disable the issue tracker.
